import type {
  Attack,
  EngineSnapshot,
  Entity,
  EntityDetail,
  GlobalStats,
  LiveAlert,
  LpProtectionSnapshot,
  PoolToxicity,
  RouteRecommendation,
  RouteRisk,
  SystemStatus,
} from "@/lib/api";

const now = Date.now();

const entities: Entity[] = [
  {
    id: "entity_b91_alpha",
    label: "B91 Sandwich Cluster",
    operator_wallet: "b91MkNr9Z7JQNDYUbMuA5vfP3FDtCBVxKh7vGPnP9bm",
    first_seen: new Date(now - 6 * 24 * 60 * 60 * 1000).toISOString(),
    last_seen: new Date(now - 2 * 60 * 1000).toISOString(),
    total_profit_usd: 184230,
    profit_24h_usd: 22480,
    profit_7d_usd: 118400,
    attack_count: 392,
    victim_count: 307,
    dominant_strategy: "sandwich",
    strategies_used: ["sandwich", "backrun"],
    risk_score: 0.92,
    fee_aggression: 0.87,
    position_dominance: 0.91,
    pool_concentration: 0.82,
    profit_consistency: 0.88,
    wallet_count: 4,
    sample_wallets: [
      "b91MkNr9Z7JQNDYUbMuA5vfP3FDtCBVxKh7vGPnP9bm",
      "9vaFZf1V4zW8j5n4U8w7v7d2x8yT8s4T1r7qX5mA9uP",
    ],
  },
  {
    id: "entity_orca_arb",
    label: "Orca Cross-Pool Arb",
    operator_wallet: "ARBotXVjkWdx9jQ7xNfLJjP4G7Xsdf9kPNsVMFf3k5z",
    first_seen: new Date(now - 10 * 24 * 60 * 60 * 1000).toISOString(),
    last_seen: new Date(now - 4 * 60 * 1000).toISOString(),
    total_profit_usd: 128940,
    profit_24h_usd: 16420,
    profit_7d_usd: 84210,
    attack_count: 514,
    victim_count: 0,
    dominant_strategy: "arbitrage",
    strategies_used: ["arbitrage"],
    risk_score: 0.74,
    fee_aggression: 0.69,
    position_dominance: 0.65,
    pool_concentration: 0.72,
    profit_consistency: 0.93,
    wallet_count: 3,
    sample_wallets: [
      "ARBotXVjkWdx9jQ7xNfLJjP4G7Xsdf9kPNsVMFf3k5z",
      "52nqv4Qk9UPkC91g3jPQt4P4mTVXxb93x7m7GYz9EWxJ",
    ],
  },
  {
    id: "entity_jit_labs",
    label: "JIT Liquidity Desk",
    operator_wallet: "J1TLabsT7Q2m3LQm1w3sB2c6m8bQ7rN6v2cW8x4z7kL",
    first_seen: new Date(now - 14 * 24 * 60 * 60 * 1000).toISOString(),
    last_seen: new Date(now - 11 * 60 * 1000).toISOString(),
    total_profit_usd: 73120,
    profit_24h_usd: 9080,
    profit_7d_usd: 40210,
    attack_count: 141,
    victim_count: 24,
    dominant_strategy: "jit",
    strategies_used: ["jit", "arbitrage"],
    risk_score: 0.61,
    fee_aggression: 0.58,
    position_dominance: 0.54,
    pool_concentration: 0.77,
    profit_consistency: 0.81,
    wallet_count: 2,
    sample_wallets: [
      "J1TLabsT7Q2m3LQm1w3sB2c6m8bQ7rN6v2cW8x4z7kL",
      "7yCkPp9J4mSxQ8Kk4bP8nS3rU2vY5fL6tP1jN7wR2dM",
    ],
  },
  {
    id: "entity_launch_hunter",
    label: "Launch Hunter Cluster",
    operator_wallet: "L4unch9pQx3Vt7hD2nM8kP1sR5wY9aF4uJ6cB2mN8qK",
    first_seen: new Date(now - 4 * 24 * 60 * 60 * 1000).toISOString(),
    last_seen: new Date(now - 7 * 60 * 1000).toISOString(),
    total_profit_usd: 44120,
    profit_24h_usd: 6120,
    profit_7d_usd: 22140,
    attack_count: 88,
    victim_count: 12,
    dominant_strategy: "liquidity_snipe" as any,
    strategies_used: ["liquidity_snipe" as any, "liquidity_drain" as any],
    risk_score: 0.67,
    fee_aggression: 0.64,
    position_dominance: 0.72,
    pool_concentration: 0.84,
    profit_consistency: 0.73,
    wallet_count: 3,
    sample_wallets: [
      "L4unch9pQx3Vt7hD2nM8kP1sR5wY9aF4uJ6cB2mN8qK",
      "9sN1p3R8uD5mQ2kC7wX4aB6tY1vP8jL3fH2gM5zN7qR",
    ],
  },
];

const attacks: Attack[] = [
  {
    id: 1,
    attack_type: "sandwich",
    slot: 329800012,
    block_time: new Date(now - 35 * 1000).toISOString(),
    validator: "Jito-Validator-Alpha",
    attacker_wallet: entities[0].sample_wallets[0],
    entity_id: entities[0].id,
    entity_label: entities[0].label,
    entity_risk: entities[0].risk_score,
    victim_wallet: "5fHq3Vn2D8sW4mK1pQ7xT9zL2nR4vB6cD8eF1gH2jK3",
    victim_loss_usd: 412.17,
    pool_address: "route:raydium_amm:So11111111111111111111111111111111111111112->EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    token_mint: "So11111111111111111111111111111111111111112",
    profit_usd: 1382.4,
    tip_lamports: 190000,
    confidence: 0.94,
    detector: "parsed_swap_sandwich",
    evidence: [
      "same pool route detected around victim swap",
      "attacker reappeared with reverse direction after victim",
      "price impact and profit leg confirmed",
    ],
    frontrun_tx: "3o8dSandwichFront111111111111111111111111111111",
    victim_tx: "7r2vVictim111111111111111111111111111111111111",
    backrun_tx: "5n9kSandwichBack11111111111111111111111111111",
  },
  {
    id: 2,
    attack_type: "arbitrage",
    slot: 329800011,
    block_time: new Date(now - 95 * 1000).toISOString(),
    validator: "Stakewiz-Pro-12",
    attacker_wallet: entities[1].sample_wallets[0],
    entity_id: entities[1].id,
    entity_label: entities[1].label,
    entity_risk: entities[1].risk_score,
    victim_wallet: null,
    victim_loss_usd: null,
    pool_address: "venue:orca_whirlpool:EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v->So11111111111111111111111111111111111111112",
    token_mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    profit_usd: 672.08,
    tip_lamports: 94000,
    confidence: 0.88,
    detector: "parsed_swap_arbitrage",
    evidence: [
      "same signer touched multiple pools",
      "stablecoin profit leg observed",
      "route-aware parsed swap candidate",
    ],
    frontrun_tx: null,
    victim_tx: null,
    backrun_tx: null,
  },
  {
    id: 3,
    attack_type: "jit",
    slot: 329800010,
    block_time: new Date(now - 3 * 60 * 1000).toISOString(),
    validator: "Jito-Validator-Beta",
    attacker_wallet: entities[2].sample_wallets[0],
    entity_id: entities[2].id,
    entity_label: entities[2].label,
    entity_risk: entities[2].risk_score,
    victim_wallet: "9dVg4tR2mL8pZ6qW4vH2dT7kB1sN9aQ3cF5eJ7uP1mR",
    victim_loss_usd: 145.26,
    pool_address: "venue:meteora_dlmm:So11111111111111111111111111111111111111112->EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    token_mint: null,
    profit_usd: 518.33,
    tip_lamports: 123000,
    confidence: 0.86,
    detector: "raw_delta_jit",
    evidence: [
      "in-slot LP add/remove pattern detected",
      "victim swap observed between LP legs",
      "profit extracted on removal leg",
    ],
    frontrun_tx: "8m2pJitAdd11111111111111111111111111111111111",
    victim_tx: "4u6nVictimSwap1111111111111111111111111111111",
    backrun_tx: "2q9rJitRemove11111111111111111111111111111111",
  },
  {
    id: 4,
    attack_type: "liquidity_snipe",
    slot: 329800009,
    block_time: new Date(now - 4 * 60 * 1000).toISOString(),
    validator: "Jito-Validator-Gamma",
    attacker_wallet: entities[3].sample_wallets[0],
    entity_id: entities[3].id,
    entity_label: entities[3].label,
    entity_risk: entities[3].risk_score,
    victim_wallet: "PoolDeployr9H2mQ7sL1vB4xD6nR3wT8pC5jK7yM2fQ4",
    victim_loss_usd: null,
    pool_address: "venue:raydium_launchpad:So11111111111111111111111111111111111111112->LaunchToken111111111111111111111111111111",
    token_mint: "LaunchToken111111111111111111111111111111",
    profit_usd: null,
    tip_lamports: 164000,
    confidence: 0.88,
    detector: "launch_liquidity_snipe",
    evidence: [
      "new pool creation was followed immediately by the first buy",
      "buy landed in the same slot as initialization",
      "launch-sensitive route showed first-fill capture behavior",
    ],
    frontrun_tx: "LaunchCreate1111111111111111111111111111111111",
    victim_tx: "LaunchFirstBuy11111111111111111111111111111111",
    backrun_tx: null,
  },
  {
    id: 5,
    attack_type: "liquidity_drain",
    slot: 329800008,
    block_time: new Date(now - 6 * 60 * 1000).toISOString(),
    validator: "Jito-Validator-Gamma",
    attacker_wallet: entities[3].sample_wallets[1],
    entity_id: entities[3].id,
    entity_label: entities[3].label,
    entity_risk: entities[3].risk_score,
    victim_wallet: null,
    victim_loss_usd: null,
    pool_address: "venue:raydium_amm:DrainToken111111111111111111111111111111->So11111111111111111111111111111111111111112",
    token_mint: "DrainToken111111111111111111111111111111",
    profit_usd: 1920.42,
    tip_lamports: 72000,
    confidence: 0.9,
    detector: "liquidity_drain_with_dump",
    evidence: [
      "liquidity was removed aggressively from the pool surface",
      "same signer followed with a dump-style swap shortly after removal",
      "removal looked non-passive and materially destabilizing",
    ],
    frontrun_tx: "DrainRemove111111111111111111111111111111111",
    victim_tx: null,
    backrun_tx: "DrainDump1111111111111111111111111111111111",
  },
];

const pools: PoolToxicity[] = [
  {
    pool_address: attacks[0].pool_address,
    epoch: 712,
    protocol: "raydium",
    sandwich_count: 81,
    arbitrage_count: 12,
    jit_count: 3,
    total_attacks: 104,
    total_extracted_usd: 48810,
    unique_attackers: 9,
    toxicity_score: 86,
    top_entity_id: entities[0].id,
    top_entity_label: entities[0].label,
    top_entity_risk: entities[0].risk_score,
    lvr_proxy_score: 78,
    adverse_selection_intensity: 84,
    stale_quote_arb_frequency: 12,
    lp_drag_estimate_usd: 36119,
    toxic_to_benign_volume_ratio: 6.14,
    quote_freshness_stress: 81,
    saved_fee_bps_if_segmented: 9.5,
    primary_cause: "sandwich pressure",
    reason_codes: ["high_sandwich_concentration", "lp_adverse_selection", "toxic_flow_dominance"],
  },
  {
    pool_address: attacks[1].pool_address,
    epoch: 712,
    protocol: "orca",
    sandwich_count: 6,
    arbitrage_count: 74,
    jit_count: 11,
    total_attacks: 97,
    total_extracted_usd: 39240,
    unique_attackers: 14,
    toxicity_score: 69,
    top_entity_id: entities[1].id,
    top_entity_label: entities[1].label,
    top_entity_risk: entities[1].risk_score,
    lvr_proxy_score: 72,
    adverse_selection_intensity: 63,
    stale_quote_arb_frequency: 76,
    lp_drag_estimate_usd: 29037.6,
    toxic_to_benign_volume_ratio: 2.23,
    quote_freshness_stress: 71,
    saved_fee_bps_if_segmented: 7.6,
    primary_cause: "stale quote arbitrage",
    reason_codes: ["stale_quote_pickups", "lp_adverse_selection"],
  },
  {
    pool_address: attacks[2].pool_address,
    epoch: 712,
    protocol: "meteora",
    sandwich_count: 9,
    arbitrage_count: 17,
    jit_count: 22,
    total_attacks: 58,
    total_extracted_usd: 18490,
    unique_attackers: 6,
    toxicity_score: 58,
    top_entity_id: entities[2].id,
    top_entity_label: entities[2].label,
    top_entity_risk: entities[2].risk_score,
    lvr_proxy_score: 54,
    adverse_selection_intensity: 51,
    stale_quote_arb_frequency: 29,
    lp_drag_estimate_usd: 13682.6,
    toxic_to_benign_volume_ratio: 1.38,
    quote_freshness_stress: 57,
    saved_fee_bps_if_segmented: 6.1,
    primary_cause: "jit liquidity pressure",
    reason_codes: ["bundle_lane_pressure", "monitor_surface"],
  },
];

const routeRisks: RouteRisk[] = [
  {
    route_key: attacks[0].pool_address,
    route_kind: "route",
    protocol: "raydium_amm",
    label: "RAYDIUM_AMM route • SOL / USDC",
    sandwich_count: 81,
    arbitrage_count: 12,
    jit_count: 3,
    liquidation_count: 0,
    backrun_count: 18,
    total_attacks: 122,
    total_extracted_usd: 62450,
    unique_attackers: 11,
    avg_confidence: 91,
    bundle_share: 67,
    risk_score: 93,
    recommendation: "avoid",
    execution_quality_score: 18,
    toxic_flow_rate: 91,
    realized_slippage_bps: 14.8,
    stale_quote_pickup_rate: 52,
    quote_freshness_ms: 118,
    markout_1s_bps: 9.6,
    markout_5s_bps: 15.2,
    markout_30s_bps: 20.4,
    flow_quality_score: 12,
    toxicity_probability: 95,
    retail_likelihood: 6,
    lp_adverse_selection_probability: 88,
    lvr_proxy_score: 82,
    priority_fee_pressure: 56,
    validator_markout_quality: 22,
    source_hint: "aggregator-routed",
    recommended_max_notional_usd: 14000,
    estimated_savings_bps: 11.4,
    estimated_savings_usd: 15.96,
    order_flow_imbalance: 58.4,
    lp_annual_loss_rate_pct: 28.2,
    lp_annual_loss_usd_estimate: 3948,
    policy_action: "avoid",
    reason_codes: ["high_sandwich_concentration", "bundle_lane_pressure", "markout_deterioration", "lp_adverse_selection"],
    decomposition: [
      { label: "sandwich_concentration", value: 66 },
      { label: "stale_quote_pickups", value: 52 },
      { label: "bundle_pressure", value: 67 },
      { label: "markout_deterioration", value: 61 },
      { label: "lp_adverse_selection", value: 82 },
    ],
  },
  {
    route_key: attacks[1].pool_address,
    route_kind: "venue",
    protocol: "orca_whirlpool",
    label: "ORCA_WHIRLPOOL venue • USDC / SOL",
    sandwich_count: 6,
    arbitrage_count: 74,
    jit_count: 11,
    liquidation_count: 0,
    backrun_count: 9,
    total_attacks: 100,
    total_extracted_usd: 41820,
    unique_attackers: 14,
    avg_confidence: 86,
    bundle_share: 44,
    risk_score: 71,
    recommendation: "penalize",
    execution_quality_score: 47,
    toxic_flow_rate: 61,
    realized_slippage_bps: 7.2,
    stale_quote_pickup_rate: 79,
    quote_freshness_ms: 294,
    markout_1s_bps: 4.6,
    markout_5s_bps: 8.7,
    markout_30s_bps: 12.5,
    flow_quality_score: 43,
    toxicity_probability: 67,
    retail_likelihood: 24,
    lp_adverse_selection_probability: 73,
    lvr_proxy_score: 76,
    priority_fee_pressure: 38,
    validator_markout_quality: 44,
    source_hint: "searcher-bot",
    recommended_max_notional_usd: 52000,
    estimated_savings_bps: 6.2,
    estimated_savings_usd: 32.24,
    order_flow_imbalance: 34.1,
    lp_annual_loss_rate_pct: 17.6,
    lp_annual_loss_usd_estimate: 9152,
    policy_action: "reroute",
    reason_codes: ["stale_quote_pickups", "lp_adverse_selection"],
    decomposition: [
      { label: "sandwich_concentration", value: 6 },
      { label: "stale_quote_pickups", value: 79 },
      { label: "bundle_pressure", value: 44 },
      { label: "markout_deterioration", value: 38 },
      { label: "lp_adverse_selection", value: 76 },
    ],
  },
  {
    route_key: attacks[2].pool_address,
    route_kind: "venue",
    protocol: "meteora_dlmm",
    label: "METEORA_DLMM venue • SOL / USDC",
    sandwich_count: 9,
    arbitrage_count: 17,
    jit_count: 22,
    liquidation_count: 2,
    backrun_count: 5,
    total_attacks: 55,
    total_extracted_usd: 22140,
    unique_attackers: 7,
    avg_confidence: 84,
    bundle_share: 38,
    risk_score: 61,
    recommendation: "penalize",
    execution_quality_score: 58,
    toxic_flow_rate: 54,
    realized_slippage_bps: 5.8,
    stale_quote_pickup_rate: 34,
    quote_freshness_ms: 362,
    markout_1s_bps: 3.4,
    markout_5s_bps: 6.5,
    markout_30s_bps: 9.1,
    flow_quality_score: 52,
    toxicity_probability: 59,
    retail_likelihood: 31,
    lp_adverse_selection_probability: 49,
    lvr_proxy_score: 52,
    priority_fee_pressure: 34,
    validator_markout_quality: 55,
    source_hint: "bundle-lane",
    recommended_max_notional_usd: 71000,
    estimated_savings_bps: 4.1,
    estimated_savings_usd: 29.11,
    order_flow_imbalance: 22.7,
    lp_annual_loss_rate_pct: 12.1,
    lp_annual_loss_usd_estimate: 8591,
    policy_action: "penalize",
    reason_codes: ["bundle_lane_pressure", "monitor_surface"],
    decomposition: [
      { label: "sandwich_concentration", value: 16 },
      { label: "stale_quote_pickups", value: 34 },
      { label: "bundle_pressure", value: 38 },
      { label: "markout_deterioration", value: 27 },
      { label: "lp_adverse_selection", value: 52 },
    ],
  },
];

const routeRecommendations: RouteRecommendation[] = [
  {
    input_mint: "So11111111111111111111111111111111111111112",
    output_mint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
    recommended_routes: [
      {
        route_key: attacks[2].pool_address,
        label: "METEORA_DLMM venue • SOL / USDC",
        protocol: "meteora_dlmm",
        recommendation: "monitor",
        risk_score: 61,
        rationale: [
          "currently safer than the most toxic route in this pair",
          "bundle exposure remains moderate relative to the raydium route",
        ],
      },
    ],
    avoid_routes: [
      {
        route_key: attacks[0].pool_address,
        label: "RAYDIUM_AMM route • SOL / USDC",
        protocol: "raydium_amm",
        risk_score: 93,
        rationale: [
          "repeat sandwich pressure is materially elevated",
          "bundle-aligned execution concentration is high",
        ],
      },
    ],
  },
];

const liveAlerts: LiveAlert[] = attacks.map((attack) => ({
  id: attack.id,
  attack_type: attack.attack_type,
  severity:
    attack.attack_type === "sandwich" && (attack.victim_loss_usd ?? 0) >= 100 ? "critical" : attack.confidence >= 0.86 ? "high" : "medium",
  summary: `${routeRisks.find((route) => route.route_key === attack.pool_address)?.label ?? attack.pool_address} ${attack.attack_type} activity detected`,
  action:
    attack.attack_type === "sandwich" && (attack.victim_loss_usd ?? 0) >= 100
      ? "block"
      : (attack.tip_lamports ?? 0) >= 120_000 || attack.validator.toLowerCase().includes("jito")
        ? "penalize"
        : "monitor",
  route_key: attack.pool_address,
  route_label: routeRisks.find((route) => route.route_key === attack.pool_address)?.label ?? attack.pool_address,
  protocol: routeRisks.find((route) => route.route_key === attack.pool_address)?.protocol ?? null,
  validator: attack.validator,
  attacker_wallet: attack.attacker_wallet,
  confidence: Number((attack.confidence * 100).toFixed(1)),
  bundle_likelihood:
    attack.validator.toLowerCase().includes("jito") || (attack.tip_lamports ?? 0) >= 120_000 ? 64 : 22,
  block_time: attack.block_time,
  rationale: [
    `${attack.attack_type} detector fired at ${(attack.confidence * 100).toFixed(0)}% confidence`,
    attack.validator.toLowerCase().includes("jito") ? "jito-aligned execution lane observed" : "standard execution lane observed",
    attack.victim_loss_usd
      ? `estimated user harm: $${attack.victim_loss_usd.toFixed(0)}`
      : `estimated extracted value: $${(attack.profit_usd ?? 0).toFixed(0)}`,
  ],
}));

export const demoStats: GlobalStats = {
  total_attacks: attacks.length,
  attacks_24h: attacks.length,
  attacks_1h: attacks.length,
  total_extracted_usd: attacks.reduce((sum, attack) => sum + (attack.profit_usd ?? 0), 0),
  extracted_24h: attacks.reduce((sum, attack) => sum + (attack.profit_usd ?? 0), 0),
  total_entities: entities.length,
  total_wallets: new Set(attacks.map((attack) => attack.attacker_wallet)).size,
  total_victims: new Set(attacks.map((attack) => attack.victim_wallet).filter(Boolean)).size,
  sandwich_count: attacks.filter((attack) => attack.attack_type === "sandwich").length,
  arb_count: attacks.filter((attack) => attack.attack_type === "arbitrage").length,
  jit_count: attacks.filter((attack) => attack.attack_type === "jit").length,
  liquidity_snipe_count: attacks.filter((attack) => attack.attack_type === "liquidity_snipe").length,
  liquidity_drain_count: attacks.filter((attack) => attack.attack_type === "liquidity_drain").length,
};

export const demoSystemStatus: SystemStatus = {
  mode: "fallback",
  heliusConfigured: false,
  started: false,
  syncing: false,
  lastProcessedSlot: null,
  latestChainSlot: null,
  blocksProcessed: 0,
  attacksDetected: attacks.length,
  lastSyncAt: null,
  lastError: "Backend unreachable. Showing demo intelligence feed.",
  lastBlockProcessingMs: null,
  avgBlockProcessingMs: null,
  recentMetrics: {
    candidateRows: 18,
    detectedAttacks: attacks.length,
    parsedTransactions: 18,
    parsedSwaps: 9,
    rawSlotTxs: 42,
    sandwichCandidates: 2,
    arbitrageCandidates: 1,
    jitCandidates: 1,
    liquidationCandidates: 0,
    liquiditySnipeCandidates: 1,
    liquidityDrainCandidates: 1,
    suspiciousCandidates: 3,
    backrunCandidates: 1,
  },
  recentAttackPreview: attacks.map((attack) => ({
    attack_type: attack.attack_type,
    detector: attack.detector ?? "demo",
    confidence: attack.confidence,
    slot: attack.slot,
  })),
};

export const demoEngineHistory: EngineSnapshot[] = Array.from({ length: 12 }, (_, index) => ({
  id: index + 1,
  mode: "fallback",
  last_processed_slot: 329800000 + index * 3,
  latest_chain_slot: 329800002 + index * 3,
  blocks_processed: 30 + index * 4,
  attacks_detected: Math.min(attacks.length + index, 18),
  parsed_transactions: 25 + index * 3,
  parsed_swaps: 10 + index * 2,
  raw_slot_txs: 90 + index * 5,
  sandwich_candidates: 2 + (index % 3),
  arbitrage_candidates: 1 + (index % 2),
  jit_candidates: 1,
  liquidation_candidates: index % 2,
  liquidity_snipe_candidates: index % 2,
  liquidity_drain_candidates: 1 + (index % 2),
  suspicious_candidates: 2 + (index % 2),
  backrun_candidates: 1 + (index % 2),
  last_error: null,
  created_at: new Date(now - index * 5 * 60 * 1000).toISOString(),
}));

export function getDemoAttacks(params?: {
  type?: string;
  pool?: string;
  protocol?: string;
  limit?: string;
  since?: string;
}): Attack[] {
  let result = [...attacks, ...orcaAttacks].sort(
    (a, b) => new Date(b.block_time).getTime() - new Date(a.block_time).getTime(),
  );

  if (params?.type) result = result.filter((attack) => attack.attack_type === params.type);
  if (params?.pool) result = result.filter((attack) => attack.pool_address === params.pool);
  if (params?.protocol) {
    const protocol = params.protocol.toLowerCase();
    result = result.filter((attack) =>
      attack.protocol?.toLowerCase().includes(protocol) ||
      attack.pool_address.toLowerCase().includes(protocol) ||
      attack.surface_label?.toLowerCase().includes(protocol),
    );
  }
  if (params?.since) {
    const since = new Date(params.since).getTime();
    result = result.filter((attack) => new Date(attack.block_time).getTime() > since);
  }

  const limit = Number.parseInt(params?.limit ?? "50", 10) || 50;
  return result.slice(0, limit);
}

export function getDemoEntities(params?: {
  strategy?: string;
  min_risk?: string;
  sort?: string;
  limit?: string;
}): Entity[] {
  let result = [...entities];

  if (params?.strategy) {
    result = result.filter((entity) => entity.strategies_used.includes(params.strategy!));
  }

  if (params?.min_risk) {
    const minRisk = Number.parseFloat(params.min_risk);
    result = result.filter((entity) => entity.risk_score >= minRisk);
  }

  if (params?.sort === "attacks") {
    result.sort((a, b) => b.attack_count - a.attack_count);
  } else if (params?.sort === "risk") {
    result.sort((a, b) => b.risk_score - a.risk_score);
  } else {
    result.sort((a, b) => b.total_profit_usd - a.total_profit_usd);
  }

  const limit = Number.parseInt(params?.limit ?? "50", 10) || 50;
  return result.slice(0, limit);
}

export function getDemoEntity(id: string): EntityDetail | null {
  const entity = entities.find((item) => item.id === id);
  if (!entity) return null;

  const recent_attacks = attacks.filter((attack) => attack.entity_id === id);
  const related_surfaces = pools
    .filter((pool) => pool.top_entity_id === id)
    .map((pool, index) => ({
      surface: pool.pool_address,
      wallet_count: Math.max(2, entity.wallet_count - (index > 1 ? 1 : 0)),
      attacks: pool.total_attacks,
      total_profit: pool.total_extracted_usd,
    }));
  return {
    entity,
    wallets: entity.sample_wallets.map((wallet, index) => ({
      wallet,
      role: index === 0 ? "operator" : "executor",
      tx_count: 40 - index * 10,
      operator_label: index === 0 ? entity.label : null,
    })),
    recent_attacks,
    targeted_pools: pools
      .filter((pool) => pool.top_entity_id === id)
      .map((pool) => ({
        pool_address: pool.pool_address,
        attack_count: pool.total_attacks,
        total_profit: pool.total_extracted_usd,
      })),
    validator_correlation: recent_attacks.map((attack) => ({
      validator: attack.validator,
      attacks: 1,
      exposure_share: Number((100 / Math.max(1, recent_attacks.length)).toFixed(1)),
      validator_risk: entity.risk_score,
      observed_sandwich_rate: entity.dominant_strategy === "sandwich" ? 62 : 18,
      stake_centralization_risk: entity.risk_score >= 0.7 ? 71 : 44,
      recommended_action: entity.risk_score >= 0.7 ? "reroute" : "monitor",
    })),
    cluster_evidence: {
      shared_surface_count: related_surfaces.length,
      shared_validator_count: Math.max(1, Math.min(entity.wallet_count, 3)),
      shared_strategy_count: entity.strategies_used.length,
      coordinated_window_count: Math.max(2, Math.round(entity.attack_count / 6)),
    },
    related_surfaces,
    profit_timeline: Array.from({ length: 7 }, (_, index) => ({
      day: new Date(now - (6 - index) * 24 * 60 * 60 * 1000).toISOString(),
      profit: Math.round(entity.profit_7d_usd / 7),
      attacks: Math.max(1, Math.round(entity.attack_count / 14)),
    })),
  };
}

export function getDemoPools(limit = 50): PoolToxicity[] {
  return [...pools, ...orcaPools].slice(0, limit);
}

export function getDemoRouteRisks(limit = 25): RouteRisk[] {
  return [...routeRisks, ...orcaRoutes].slice(0, limit);
}

export function getDemoRouteRecommendations(limit = 12): RouteRecommendation[] {
  return [...routeRecommendations].slice(0, limit);
}

export function getDemoLiveAlerts(limit = 20): LiveAlert[] {
  return [...liveAlerts].slice(0, limit);
}

// ─── Raydium local demo data (shown when chain feed is offline) ──────────────

const SOL  = "So11111111111111111111111111111111111111112";
const USDC = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";
const USDT = "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB";
const RAY  = "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R";
const BONK = "DezXAZ8z7PnrnRJjz3wXBoRgixCa6xjnB7YaB1pPB263";

const RK_CPMM_SOL_USDC  = `route:raydium_cpmm:${SOL}->${USDC}`;
const RK_AMM_SOL_USDT   = `route:raydium_amm:${SOL}->${USDT}`;
const RK_CLMM_SOL_USDC  = `venue:raydium_clmm:${SOL}->${USDC}`;
const RK_CLMM_RAY_SOL   = `venue:raydium_clmm:${RAY}->${SOL}`;
const RK_LAUNCH_BONK    = `venue:raydium_launchlab:${BONK}->${SOL}`;
const RK_STABLE_USDC_USDT = `venue:raydium_stable_amm:${USDC}->${USDT}`;

const raydiumAttacks: Attack[] = [
  {
    id: 101,
    attack_type: "sandwich",
    slot: 330100041,
    block_time: new Date(now - 18 * 1000).toISOString(),
    validator: "Jito-Validator-Alpha",
    attacker_wallet: "MEVbotRay1aXXGkm8vZq3sNPu7TdC5BkF2hV9wQpJrY4",
    entity_id: null,
    entity_label: null,
    entity_risk: null,
    victim_wallet: "tRad3rSo1Wp8nQ4mD2vK7bL1xF3cT9eH5jR6yP2gM0s",
    victim_loss_usd: 892.44,
    pool_address: RK_CPMM_SOL_USDC,
    protocol: "raydium_cpmm",
    surface_label: "Raydium CPMM SOL/USDC",
    token_mint: SOL,
    profit_usd: 2341.18,
    tip_lamports: 210000,
    confidence: 0.96,
    detector: "parsed_swap_sandwich",
    execution_lane: "jito-aligned",
    bundle_likelihood: 0.84,
    evidence: [
      "frontrun and backrun share the same signer across slot boundaries",
      "victim swap sandwiched between two opposite-direction swaps",
      "price impact of 0.42% observed on victim leg",
    ],
    frontrun_tx: "3RayCPMMfront1111111111111111111111111111111111",
    victim_tx: "7VictimSwapRay111111111111111111111111111111111",
    backrun_tx: "5RayCPMMback11111111111111111111111111111111111",
  },
  {
    id: 102,
    attack_type: "sandwich",
    slot: 330100039,
    block_time: new Date(now - 52 * 1000).toISOString(),
    validator: "Jito-Validator-Beta",
    attacker_wallet: "MEVbotRay1aXXGkm8vZq3sNPu7TdC5BkF2hV9wQpJrY4",
    entity_id: null,
    entity_label: null,
    entity_risk: null,
    victim_wallet: "tRad3rWa113tBv2rNkM5sQ8xL4dJ7cP1eF6gH9wY3zA0",
    victim_loss_usd: 1247.66,
    pool_address: RK_CPMM_SOL_USDC,
    protocol: "raydium_cpmm",
    surface_label: "Raydium CPMM SOL/USDC",
    token_mint: USDC,
    profit_usd: 3182.09,
    tip_lamports: 195000,
    confidence: 0.94,
    detector: "parsed_swap_sandwich",
    execution_lane: "jito-aligned",
    bundle_likelihood: 0.81,
    evidence: [
      "double-sided sandwich confirmed via block ordering",
      "tip matches typical B91 operator fee pattern",
      "victim slippage consumed by frontrun leg",
    ],
    frontrun_tx: "4RayCPMMfront2222222222222222222222222222222222",
    victim_tx: "8VictimSwapRay222222222222222222222222222222222",
    backrun_tx: "6RayCPMMback22222222222222222222222222222222222",
  },
  {
    id: 103,
    attack_type: "sandwich",
    slot: 330100036,
    block_time: new Date(now - 2 * 60 * 1000).toISOString(),
    validator: "Stakewiz-Pro-09",
    attacker_wallet: "RAYsandw1ch3rB2cK7vM9nQ1pS4wT6xL8aD3eF5gH0jR",
    entity_id: null,
    entity_label: null,
    entity_risk: null,
    victim_wallet: "tRad3rAgg3gRouteV4bL2mP9sX7cT1eH3kF8wQ6yN5dM",
    victim_loss_usd: 431.22,
    pool_address: RK_AMM_SOL_USDT,
    protocol: "raydium_amm",
    surface_label: "Raydium AMM v4 SOL/USDT",
    token_mint: SOL,
    profit_usd: 1104.58,
    tip_lamports: 175000,
    confidence: 0.91,
    detector: "parsed_swap_sandwich",
    execution_lane: "priority-fee",
    bundle_likelihood: 0.52,
    evidence: [
      "AMM v4 pool sandwiched within a 3-slot window",
      "stale quote picked up before execution",
      "victim paid 14.2 bps above expected fill",
    ],
    frontrun_tx: "2RayAMMfront33333333333333333333333333333333333",
    victim_tx: "9VictimSwapRay333333333333333333333333333333333",
    backrun_tx: "7RayAMMback333333333333333333333333333333333333",
  },
  {
    id: 104,
    attack_type: "jit",
    slot: 330100033,
    block_time: new Date(now - 3 * 60 * 1000 - 12 * 1000).toISOString(),
    validator: "Jito-Validator-Gamma",
    attacker_wallet: "J1TliqD3skRay7vN2mQ4pL9sX1cB6wT8eK3aF5gH0yR",
    entity_id: null,
    entity_label: null,
    entity_risk: null,
    victim_wallet: "LP0wn3rC1mmV5bK2nM8sQ3xP7wT1eH4cF9gA6yR0dL",
    victim_loss_usd: 318.77,
    pool_address: RK_CLMM_SOL_USDC,
    protocol: "raydium_clmm",
    surface_label: "Raydium CLMM SOL/USDC",
    token_mint: SOL,
    profit_usd: 724.41,
    tip_lamports: 140000,
    confidence: 0.89,
    detector: "raw_delta_jit",
    execution_lane: "jito-aligned",
    bundle_likelihood: 0.77,
    evidence: [
      "in-slot add_liquidity followed by large victim swap then remove_liquidity",
      "tight tick range [129.2, 131.8] targeted specifically around execution price",
      "fee dilution estimated at 7.1 bps for passive LPs in this window",
    ],
    frontrun_tx: "1RayCLMMjitAdd44444444444444444444444444444444",
    victim_tx: "5VictimSwapRay444444444444444444444444444444444",
    backrun_tx: "3RayCLMMjitRem44444444444444444444444444444444",
  },
  {
    id: 105,
    attack_type: "jit",
    slot: 330100031,
    block_time: new Date(now - 4 * 60 * 1000 - 30 * 1000).toISOString(),
    validator: "Jito-Validator-Alpha",
    attacker_wallet: "J1TliqD3skRay7vN2mQ4pL9sX1cB6wT8eK3aF5gH0yR",
    entity_id: null,
    entity_label: null,
    entity_risk: null,
    victim_wallet: "LP0wn3rC1mmV6cL3oN9tR4yQ8xW2dB7eF0gA1hI5jK",
    victim_loss_usd: 209.14,
    pool_address: RK_CLMM_RAY_SOL,
    protocol: "raydium_clmm",
    surface_label: "Raydium CLMM RAY/SOL",
    token_mint: RAY,
    profit_usd: 481.28,
    tip_lamports: 130000,
    confidence: 0.87,
    detector: "raw_delta_jit",
    execution_lane: "jito-aligned",
    bundle_likelihood: 0.74,
    evidence: [
      "JIT liquidity add detected within 2 slots before victim swap",
      "concentrated position around execution range removed immediately after fill",
      "LP drag estimated at 5.3 bps on this tick range",
    ],
    frontrun_tx: "2RayCLMMjitAdd55555555555555555555555555555555",
    victim_tx: "6VictimSwapRay555555555555555555555555555555555",
    backrun_tx: "4RayCLMMjitRem55555555555555555555555555555555",
  },
  {
    id: 106,
    attack_type: "liquidity_snipe",
    slot: 330100028,
    block_time: new Date(now - 6 * 60 * 1000).toISOString(),
    validator: "Jito-Validator-Delta",
    attacker_wallet: "SN1p3rLaunch9pQx3Vt7hD2nM8kP1sR5wY4aF6uJ3mN",
    entity_id: null,
    entity_label: null,
    entity_risk: null,
    victim_wallet: "TokenD3pl0yr8H2mQ7sL1vB4xD6nR3wT8pC5jK2yM",
    victim_loss_usd: null,
    pool_address: RK_LAUNCH_BONK,
    protocol: "raydium_launchlab",
    surface_label: "Raydium LaunchLab BONK/SOL",
    token_mint: BONK,
    profit_usd: 4182.77,
    tip_lamports: 280000,
    confidence: 0.92,
    detector: "launch_liquidity_snipe",
    execution_lane: "jito-aligned",
    bundle_likelihood: 0.89,
    evidence: [
      "first buy landed in the same slot as pool initialization",
      "sniper wallet acquired 8.4% of initial supply at curve floor",
      "high-priority bundle submission used to front-run organic buyers",
    ],
    frontrun_tx: "LaunchInitBONK666666666666666666666666666666",
    victim_tx: "LaunchFirstBuy666666666666666666666666666666",
    backrun_tx: null,
  },
  {
    id: 107,
    attack_type: "liquidity_snipe",
    slot: 330100025,
    block_time: new Date(now - 7 * 60 * 1000 - 20 * 1000).toISOString(),
    validator: "Jito-Validator-Delta",
    attacker_wallet: "SN1p3rLaunch9pQx3Vt7hD2nM8kP1sR5wY4aF6uJ3mN",
    entity_id: null,
    entity_label: null,
    entity_risk: null,
    victim_wallet: "TokenD3pl0yr9I3nR8sM2wC5yE7oS4xT9qD6kL3zN",
    victim_loss_usd: null,
    pool_address: `venue:raydium_launchlab:WIF9tNq2mP7sR4xK8vL3cB1eH6wT5aF2gD9jM0yN->${SOL}`,
    protocol: "raydium_launchlab",
    surface_label: "Raydium LaunchLab WIF/SOL",
    token_mint: "WIF9tNq2mP7sR4xK8vL3cB1eH6wT5aF2gD9jM0yN",
    profit_usd: 2814.33,
    tip_lamports: 250000,
    confidence: 0.90,
    detector: "launch_liquidity_snipe",
    execution_lane: "jito-aligned",
    bundle_likelihood: 0.86,
    evidence: [
      "sniper captured first-fill within 400ms of curve go-live",
      "token acquired at 0% curve progress — maximum discount",
      "wallet shows repeat pattern across 14 prior LaunchLab pools",
    ],
    frontrun_tx: "LaunchInitWIF7777777777777777777777777777777",
    victim_tx: "LaunchFirstBuy777777777777777777777777777777",
    backrun_tx: null,
  },
  {
    id: 108,
    attack_type: "arbitrage",
    slot: 330100022,
    block_time: new Date(now - 9 * 60 * 1000).toISOString(),
    validator: "Stakewiz-Pro-11",
    attacker_wallet: "ARBb0tRay4vN8mQ1pL6sX2cB9wT3eK7aF0gH5yR2dJ",
    entity_id: null,
    entity_label: null,
    entity_risk: null,
    victim_wallet: null,
    victim_loss_usd: null,
    pool_address: RK_STABLE_USDC_USDT,
    protocol: "raydium_stable_amm",
    surface_label: "Raydium Stable AMM USDC/USDT",
    token_mint: USDC,
    profit_usd: 284.12,
    tip_lamports: 68000,
    confidence: 0.83,
    detector: "parsed_swap_arbitrage",
    execution_lane: "standard",
    bundle_likelihood: 0.18,
    evidence: [
      "cross-venue price imbalance exploited between Raydium and Orca stable pools",
      "same signer executed both legs within 1 slot",
      "stablecoin round-trip confirmed with net positive USDC balance",
    ],
    frontrun_tx: null,
    victim_tx: null,
    backrun_tx: null,
  },
];

const raydiumRoutes: RouteRisk[] = [
  {
    route_key: RK_CPMM_SOL_USDC,
    route_kind: "route",
    protocol: "raydium_cpmm",
    label: "Raydium CPMM SOL/USDC",
    sandwich_count: 94,
    arbitrage_count: 18,
    jit_count: 4,
    liquidation_count: 0,
    backrun_count: 22,
    total_attacks: 138,
    total_extracted_usd: 78420,
    unique_attackers: 13,
    avg_confidence: 93,
    bundle_share: 71,
    risk_score: 96,
    recommendation: "avoid",
    execution_quality_score: 14,
    toxic_flow_rate: 94,
    realized_slippage_bps: 16.2,
    stale_quote_pickup_rate: 58,
    quote_freshness_ms: 104,
    markout_1s_bps: 11.2,
    markout_5s_bps: 17.8,
    markout_30s_bps: 23.1,
    flow_quality_score: 9,
    toxicity_probability: 97,
    retail_likelihood: 4,
    lp_adverse_selection_probability: 91,
    lvr_proxy_score: 88,
    priority_fee_pressure: 62,
    validator_markout_quality: 18,
    source_hint: "aggregator-routed",
    recommended_max_notional_usd: 11000,
    estimated_savings_bps: 13.6,
    estimated_savings_usd: 184200,
    order_flow_imbalance: 64.2,
    lp_annual_loss_rate_pct: 31.4,
    lp_annual_loss_usd_estimate: 4812,
    policy_action: "avoid",
    reason_codes: ["high_sandwich_concentration", "bundle_lane_pressure", "markout_deterioration", "lp_adverse_selection"],
    decomposition: [
      { label: "sandwich_concentration", value: 78 },
      { label: "stale_quote_pickups", value: 58 },
      { label: "bundle_pressure", value: 71 },
      { label: "markout_deterioration", value: 67 },
      { label: "lp_adverse_selection", value: 88 },
    ],
  },
  {
    route_key: RK_AMM_SOL_USDT,
    route_kind: "route",
    protocol: "raydium_amm",
    label: "Raydium AMM v4 SOL/USDT",
    sandwich_count: 61,
    arbitrage_count: 24,
    jit_count: 7,
    liquidation_count: 1,
    backrun_count: 14,
    total_attacks: 107,
    total_extracted_usd: 54180,
    unique_attackers: 10,
    avg_confidence: 88,
    bundle_share: 59,
    risk_score: 82,
    recommendation: "penalize",
    execution_quality_score: 28,
    toxic_flow_rate: 78,
    realized_slippage_bps: 12.4,
    stale_quote_pickup_rate: 44,
    quote_freshness_ms: 142,
    markout_1s_bps: 8.8,
    markout_5s_bps: 13.6,
    markout_30s_bps: 19.2,
    flow_quality_score: 22,
    toxicity_probability: 84,
    retail_likelihood: 11,
    lp_adverse_selection_probability: 79,
    lvr_proxy_score: 74,
    priority_fee_pressure: 48,
    validator_markout_quality: 26,
    source_hint: "aggregator-routed",
    recommended_max_notional_usd: 18000,
    estimated_savings_bps: 10.4,
    estimated_savings_usd: 112400,
    order_flow_imbalance: 51.8,
    lp_annual_loss_rate_pct: 24.7,
    lp_annual_loss_usd_estimate: 3941,
    policy_action: "penalize",
    reason_codes: ["high_sandwich_concentration", "stale_quote_pickups", "lp_adverse_selection"],
    decomposition: [
      { label: "sandwich_concentration", value: 62 },
      { label: "stale_quote_pickups", value: 44 },
      { label: "bundle_pressure", value: 59 },
      { label: "markout_deterioration", value: 52 },
      { label: "lp_adverse_selection", value: 79 },
    ],
  },
  {
    route_key: RK_CLMM_SOL_USDC,
    route_kind: "venue",
    protocol: "raydium_clmm",
    label: "Raydium CLMM SOL/USDC",
    sandwich_count: 8,
    arbitrage_count: 19,
    jit_count: 38,
    liquidation_count: 2,
    backrun_count: 6,
    total_attacks: 73,
    total_extracted_usd: 29640,
    unique_attackers: 7,
    avg_confidence: 86,
    bundle_share: 64,
    risk_score: 74,
    recommendation: "penalize",
    execution_quality_score: 41,
    toxic_flow_rate: 66,
    realized_slippage_bps: 7.6,
    stale_quote_pickup_rate: 31,
    quote_freshness_ms: 218,
    markout_1s_bps: 5.2,
    markout_5s_bps: 9.4,
    markout_30s_bps: 14.7,
    flow_quality_score: 34,
    toxicity_probability: 71,
    retail_likelihood: 18,
    lp_adverse_selection_probability: 68,
    lvr_proxy_score: 63,
    priority_fee_pressure: 41,
    validator_markout_quality: 38,
    source_hint: "bundle-lane",
    recommended_max_notional_usd: 38000,
    estimated_savings_bps: 7.9,
    estimated_savings_usd: 74600,
    order_flow_imbalance: 38.6,
    lp_annual_loss_rate_pct: 18.9,
    lp_annual_loss_usd_estimate: 6741,
    policy_action: "penalize",
    reason_codes: ["bundle_lane_pressure", "jit_window_exposure", "lp_adverse_selection"],
    decomposition: [
      { label: "sandwich_concentration", value: 12 },
      { label: "stale_quote_pickups", value: 31 },
      { label: "bundle_pressure", value: 64 },
      { label: "markout_deterioration", value: 44 },
      { label: "lp_adverse_selection", value: 68 },
    ],
  },
  {
    route_key: RK_CLMM_RAY_SOL,
    route_kind: "venue",
    protocol: "raydium_clmm",
    label: "Raydium CLMM RAY/SOL",
    sandwich_count: 4,
    arbitrage_count: 31,
    jit_count: 24,
    liquidation_count: 0,
    backrun_count: 8,
    total_attacks: 67,
    total_extracted_usd: 21380,
    unique_attackers: 8,
    avg_confidence: 82,
    bundle_share: 52,
    risk_score: 63,
    recommendation: "penalize",
    execution_quality_score: 49,
    toxic_flow_rate: 58,
    realized_slippage_bps: 6.1,
    stale_quote_pickup_rate: 27,
    quote_freshness_ms: 284,
    markout_1s_bps: 3.8,
    markout_5s_bps: 7.2,
    markout_30s_bps: 11.3,
    flow_quality_score: 44,
    toxicity_probability: 62,
    retail_likelihood: 26,
    lp_adverse_selection_probability: 57,
    lvr_proxy_score: 54,
    priority_fee_pressure: 34,
    validator_markout_quality: 46,
    source_hint: "bundle-lane",
    recommended_max_notional_usd: 54000,
    estimated_savings_bps: 5.6,
    estimated_savings_usd: 51200,
    order_flow_imbalance: 29.4,
    lp_annual_loss_rate_pct: 14.2,
    lp_annual_loss_usd_estimate: 4986,
    policy_action: "penalize",
    reason_codes: ["bundle_lane_pressure", "jit_window_exposure"],
    decomposition: [
      { label: "sandwich_concentration", value: 7 },
      { label: "stale_quote_pickups", value: 27 },
      { label: "bundle_pressure", value: 52 },
      { label: "markout_deterioration", value: 36 },
      { label: "lp_adverse_selection", value: 57 },
    ],
  },
  {
    route_key: RK_LAUNCH_BONK,
    route_kind: "venue",
    protocol: "raydium_launchlab",
    label: "Raydium LaunchLab BONK/SOL",
    sandwich_count: 2,
    arbitrage_count: 6,
    jit_count: 1,
    liquidation_count: 0,
    backrun_count: 3,
    total_attacks: 22,
    total_extracted_usd: 14820,
    unique_attackers: 4,
    avg_confidence: 90,
    bundle_share: 88,
    risk_score: 71,
    recommendation: "penalize",
    execution_quality_score: 32,
    toxic_flow_rate: 71,
    realized_slippage_bps: 9.8,
    stale_quote_pickup_rate: 14,
    quote_freshness_ms: 88,
    markout_1s_bps: 6.4,
    markout_5s_bps: 11.1,
    markout_30s_bps: 16.8,
    flow_quality_score: 28,
    toxicity_probability: 74,
    retail_likelihood: 8,
    lp_adverse_selection_probability: 44,
    lvr_proxy_score: 41,
    priority_fee_pressure: 72,
    validator_markout_quality: 24,
    source_hint: "bundle-lane",
    recommended_max_notional_usd: 6000,
    estimated_savings_bps: 9.2,
    estimated_savings_usd: 28600,
    order_flow_imbalance: 48.1,
    lp_annual_loss_rate_pct: 9.4,
    lp_annual_loss_usd_estimate: 1882,
    policy_action: "reroute",
    reason_codes: ["launch_sniper_exposure", "bundle_lane_pressure", "high_priority_fee_pressure"],
    decomposition: [
      { label: "sandwich_concentration", value: 9 },
      { label: "stale_quote_pickups", value: 14 },
      { label: "bundle_pressure", value: 88 },
      { label: "markout_deterioration", value: 58 },
      { label: "lp_adverse_selection", value: 44 },
    ],
  },
  {
    route_key: RK_STABLE_USDC_USDT,
    route_kind: "venue",
    protocol: "raydium_stable_amm",
    label: "Raydium Stable AMM USDC/USDT",
    sandwich_count: 1,
    arbitrage_count: 42,
    jit_count: 0,
    liquidation_count: 0,
    backrun_count: 4,
    total_attacks: 47,
    total_extracted_usd: 6280,
    unique_attackers: 9,
    avg_confidence: 76,
    bundle_share: 22,
    risk_score: 34,
    recommendation: "monitor",
    execution_quality_score: 72,
    toxic_flow_rate: 28,
    realized_slippage_bps: 1.4,
    stale_quote_pickup_rate: 61,
    quote_freshness_ms: 480,
    markout_1s_bps: 0.9,
    markout_5s_bps: 1.8,
    markout_30s_bps: 3.2,
    flow_quality_score: 66,
    toxicity_probability: 31,
    retail_likelihood: 54,
    lp_adverse_selection_probability: 24,
    lvr_proxy_score: 19,
    priority_fee_pressure: 14,
    validator_markout_quality: 68,
    source_hint: "aggregator-routed",
    recommended_max_notional_usd: 180000,
    estimated_savings_bps: 1.4,
    estimated_savings_usd: 7400,
    order_flow_imbalance: 12.3,
    lp_annual_loss_rate_pct: 3.8,
    lp_annual_loss_usd_estimate: 912,
    policy_action: "monitor",
    reason_codes: ["stale_quote_pickups", "monitor_surface"],
    decomposition: [
      { label: "sandwich_concentration", value: 2 },
      { label: "stale_quote_pickups", value: 61 },
      { label: "bundle_pressure", value: 22 },
      { label: "markout_deterioration", value: 14 },
      { label: "lp_adverse_selection", value: 24 },
    ],
  },
];

const raydiumPools: PoolToxicity[] = [
  {
    pool_address: RK_CPMM_SOL_USDC,
    epoch: 718,
    protocol: "raydium_cpmm",
    sandwich_count: 94,
    arbitrage_count: 18,
    jit_count: 4,
    total_attacks: 138,
    total_extracted_usd: 78420,
    unique_attackers: 13,
    toxicity_score: 96,
    top_entity_id: null,
    top_entity_label: "B91 Sandwich Cluster",
    top_entity_risk: 0.94,
    lvr_proxy_score: 88,
    adverse_selection_intensity: 91,
    stale_quote_arb_frequency: 58,
    lp_drag_estimate_usd: 61280,
    toxic_to_benign_volume_ratio: 7.82,
    quote_freshness_stress: 92,
    saved_fee_bps_if_segmented: 11.4,
    primary_cause: "sandwich pressure",
    reason_codes: ["high_sandwich_concentration", "bundle_lane_pressure", "lp_adverse_selection"],
  },
  {
    pool_address: RK_AMM_SOL_USDT,
    epoch: 718,
    protocol: "raydium_amm",
    sandwich_count: 61,
    arbitrage_count: 24,
    jit_count: 7,
    total_attacks: 107,
    total_extracted_usd: 54180,
    unique_attackers: 10,
    toxicity_score: 82,
    top_entity_id: null,
    top_entity_label: "AMM Sandwich Operator",
    top_entity_risk: 0.84,
    lvr_proxy_score: 74,
    adverse_selection_intensity: 79,
    stale_quote_arb_frequency: 44,
    lp_drag_estimate_usd: 42060,
    toxic_to_benign_volume_ratio: 5.34,
    quote_freshness_stress: 81,
    saved_fee_bps_if_segmented: 9.8,
    primary_cause: "sandwich + stale quote arb",
    reason_codes: ["high_sandwich_concentration", "stale_quote_pickups"],
  },
  {
    pool_address: RK_CLMM_SOL_USDC,
    epoch: 718,
    protocol: "raydium_clmm",
    sandwich_count: 8,
    arbitrage_count: 19,
    jit_count: 38,
    total_attacks: 73,
    total_extracted_usd: 29640,
    unique_attackers: 7,
    toxicity_score: 74,
    top_entity_id: null,
    top_entity_label: "JIT Liquidity Desk",
    top_entity_risk: 0.78,
    lvr_proxy_score: 63,
    adverse_selection_intensity: 68,
    stale_quote_arb_frequency: 31,
    lp_drag_estimate_usd: 22190,
    toxic_to_benign_volume_ratio: 3.12,
    quote_freshness_stress: 64,
    saved_fee_bps_if_segmented: 8.1,
    primary_cause: "jit liquidity extraction",
    reason_codes: ["jit_window_exposure", "bundle_lane_pressure"],
  },
  {
    pool_address: RK_CLMM_RAY_SOL,
    epoch: 718,
    protocol: "raydium_clmm",
    sandwich_count: 4,
    arbitrage_count: 31,
    jit_count: 24,
    total_attacks: 67,
    total_extracted_usd: 21380,
    unique_attackers: 8,
    toxicity_score: 63,
    top_entity_id: null,
    top_entity_label: "JIT Liquidity Desk",
    top_entity_risk: 0.72,
    lvr_proxy_score: 54,
    adverse_selection_intensity: 57,
    stale_quote_arb_frequency: 27,
    lp_drag_estimate_usd: 16480,
    toxic_to_benign_volume_ratio: 2.48,
    quote_freshness_stress: 52,
    saved_fee_bps_if_segmented: 6.4,
    primary_cause: "jit + arb cross-pressure",
    reason_codes: ["jit_window_exposure", "bundle_lane_pressure"],
  },
  {
    pool_address: RK_LAUNCH_BONK,
    epoch: 718,
    protocol: "raydium_launchlab",
    sandwich_count: 2,
    arbitrage_count: 6,
    jit_count: 1,
    total_attacks: 22,
    total_extracted_usd: 14820,
    unique_attackers: 4,
    toxicity_score: 71,
    top_entity_id: null,
    top_entity_label: "Launch Hunter Cluster",
    top_entity_risk: 0.88,
    lvr_proxy_score: 41,
    adverse_selection_intensity: 44,
    stale_quote_arb_frequency: 14,
    lp_drag_estimate_usd: 8910,
    toxic_to_benign_volume_ratio: 4.61,
    quote_freshness_stress: 38,
    saved_fee_bps_if_segmented: 7.2,
    primary_cause: "launch sniper activity",
    reason_codes: ["launch_sniper_exposure", "bundle_lane_pressure"],
  },
  {
    pool_address: RK_STABLE_USDC_USDT,
    epoch: 718,
    protocol: "raydium_stable_amm",
    sandwich_count: 1,
    arbitrage_count: 42,
    jit_count: 0,
    total_attacks: 47,
    total_extracted_usd: 6280,
    unique_attackers: 9,
    toxicity_score: 34,
    top_entity_id: null,
    top_entity_label: "Cross-venue Arb Bot",
    top_entity_risk: 0.41,
    lvr_proxy_score: 19,
    adverse_selection_intensity: 24,
    stale_quote_arb_frequency: 61,
    lp_drag_estimate_usd: 3940,
    toxic_to_benign_volume_ratio: 0.84,
    quote_freshness_stress: 28,
    saved_fee_bps_if_segmented: 2.8,
    primary_cause: "stale quote arbitrage",
    reason_codes: ["stale_quote_pickups", "monitor_surface"],
  },
];

const raydiumLpProtection: LpProtectionSnapshot[] = [
  {
    pool_address: RK_CPMM_SOL_USDC,
    protocol: "raydium_cpmm",
    toxicity_score: 96,
    lvr_proxy_score: 88,
    adverse_selection_intensity: 91,
    stale_quote_arb_frequency: 58,
    lp_drag_estimate_usd: 61280,
    toxic_to_benign_volume_ratio: 7.82,
    quote_freshness_stress: 92,
    saved_fee_bps_if_segmented: 11.4,
    primary_cause: "sandwich pressure",
    reason_codes: ["high_sandwich_concentration", "bundle_lane_pressure", "lp_adverse_selection"],
  },
  {
    pool_address: RK_AMM_SOL_USDT,
    protocol: "raydium_amm",
    toxicity_score: 82,
    lvr_proxy_score: 74,
    adverse_selection_intensity: 79,
    stale_quote_arb_frequency: 44,
    lp_drag_estimate_usd: 42060,
    toxic_to_benign_volume_ratio: 5.34,
    quote_freshness_stress: 81,
    saved_fee_bps_if_segmented: 9.8,
    primary_cause: "sandwich + stale quote arb",
    reason_codes: ["high_sandwich_concentration", "stale_quote_pickups"],
  },
  {
    pool_address: RK_CLMM_SOL_USDC,
    protocol: "raydium_clmm",
    toxicity_score: 74,
    lvr_proxy_score: 63,
    adverse_selection_intensity: 68,
    stale_quote_arb_frequency: 31,
    lp_drag_estimate_usd: 22190,
    toxic_to_benign_volume_ratio: 3.12,
    quote_freshness_stress: 64,
    saved_fee_bps_if_segmented: 8.1,
    primary_cause: "jit liquidity extraction",
    reason_codes: ["jit_window_exposure", "bundle_lane_pressure"],
  },
  {
    pool_address: RK_CLMM_RAY_SOL,
    protocol: "raydium_clmm",
    toxicity_score: 63,
    lvr_proxy_score: 54,
    adverse_selection_intensity: 57,
    stale_quote_arb_frequency: 27,
    lp_drag_estimate_usd: 16480,
    toxic_to_benign_volume_ratio: 2.48,
    quote_freshness_stress: 52,
    saved_fee_bps_if_segmented: 6.4,
    primary_cause: "jit + arb cross-pressure",
    reason_codes: ["jit_window_exposure"],
  },
  {
    pool_address: RK_LAUNCH_BONK,
    protocol: "raydium_launchlab",
    toxicity_score: 71,
    lvr_proxy_score: 41,
    adverse_selection_intensity: 44,
    stale_quote_arb_frequency: 14,
    lp_drag_estimate_usd: 8910,
    toxic_to_benign_volume_ratio: 4.61,
    quote_freshness_stress: 38,
    saved_fee_bps_if_segmented: 7.2,
    primary_cause: "launch sniper activity",
    reason_codes: ["launch_sniper_exposure"],
  },
];

// ─── Orca local demo data (shown when chain feed is offline) ─────────────────

const MSOL = "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So";
const JITO = "J1toso1uCk3RLmjorhTtrVwY9HJ7X8V9yYac6Y7kGCPn";
const ORCA = "orcaEKTd8a7LKz57vaAYC5Az1Wd7Gg99j5ba87TtfF2";

const OK_WHIRL_SOL_USDC = `venue:orca_whirlpool:${SOL}->${USDC}`;
const OK_WHIRL_USDC_SOL = `venue:orca_whirlpool:${USDC}->${SOL}`;
const OK_WHIRL_MSOL_SOL = `venue:orca_whirlpool:${MSOL}->${SOL}`;
const OK_WHIRL_ORCA_SOL = `venue:orca_whirlpool:${ORCA}->${SOL}`;
const OK_WHIRL_JITO_SOL = `venue:orca_whirlpool:${JITO}->${SOL}`;
const OK_LEGACY_USDC_USDT = `route:orca_legacy_v2:${USDC}->${USDT}`;

const orcaAttacks: Attack[] = [
  {
    id: 201,
    attack_type: "jit",
    slot: 330100061,
    block_time: new Date(now - 24 * 1000).toISOString(),
    validator: "Jito-Validator-Whirlpool-01",
    attacker_wallet: "ORCAjitTickDesk7vN2mQ4pL9sX1cB6wT8eK3aF5gH0yR",
    entity_id: "entity_jit_labs",
    entity_label: "JIT Liquidity Desk",
    entity_risk: 0.81,
    victim_wallet: "OrcaLpPassive1tK7bL1xF3cT9eH5jR6yP2gM0s",
    victim_loss_usd: 388.24,
    pool_address: OK_WHIRL_SOL_USDC,
    protocol: "orca_whirlpool",
    surface_label: "Orca Whirlpool SOL/USDC 0.04%",
    token_mint: SOL,
    profit_usd: 954.12,
    tip_lamports: 168000,
    confidence: 0.95,
    detector: "raw_delta_jit_orca_whirlpool",
    execution_lane: "jito-aligned",
    bundle_likelihood: 0.82,
    evidence: [
      "Whirlpool add/swap/remove sequence landed in the same slot",
      "temporary range overlapped the active SOL/USDC tick array",
      "passive LP fee dilution estimated at 8.4 bps in the active band",
    ],
    frontrun_tx: "OrcaJitAddSOLUSDC11111111111111111111111111",
    victim_tx: "OrcaVictimSwapSOLUSDC111111111111111111111",
    backrun_tx: "OrcaJitRemoveSOLUSDC111111111111111111111",
  },
  {
    id: 202,
    attack_type: "jit",
    slot: 330100058,
    block_time: new Date(now - 72 * 1000).toISOString(),
    validator: "Jito-Validator-Whirlpool-02",
    attacker_wallet: "ORCAjitTickDesk7vN2mQ4pL9sX1cB6wT8eK3aF5gH0yR",
    entity_id: "entity_jit_labs",
    entity_label: "JIT Liquidity Desk",
    entity_risk: 0.81,
    victim_wallet: "OrcaLpPassive2mK8sQ3xP7wT1eH4cF9gA6yR0dL",
    victim_loss_usd: 276.61,
    pool_address: OK_WHIRL_MSOL_SOL,
    protocol: "orca_whirlpool",
    surface_label: "Orca Whirlpool mSOL/SOL 0.01%",
    token_mint: MSOL,
    profit_usd: 642.38,
    tip_lamports: 142000,
    confidence: 0.93,
    detector: "raw_delta_jit_orca_whirlpool",
    execution_lane: "jito-aligned",
    bundle_likelihood: 0.78,
    evidence: [
      "same signer opened a narrow position then closed after the swap",
      "tick spacing 1 pool showed high fee-capture concentration",
      "active range fee share spiked relative to passive LP share",
    ],
    frontrun_tx: "OrcaJitAddMSOLSOL222222222222222222222222",
    victim_tx: "OrcaVictimSwapMSOLSOL22222222222222222222",
    backrun_tx: "OrcaJitRemoveMSOLSOL22222222222222222222",
  },
  {
    id: 203,
    attack_type: "arbitrage",
    slot: 330100054,
    block_time: new Date(now - 2 * 60 * 1000).toISOString(),
    validator: "Stakewiz-Pro-22",
    attacker_wallet: "ORCAarbAcrossFees9pQx3Vt7hD2nM8kP1sR5wY4aF6",
    entity_id: "entity_orca_arb",
    entity_label: "Orca Cross-Pool Arb",
    entity_risk: 0.74,
    victim_wallet: null,
    victim_loss_usd: null,
    pool_address: OK_WHIRL_USDC_SOL,
    protocol: "orca_whirlpool",
    surface_label: "Orca Whirlpool USDC/SOL adaptive fee",
    token_mint: USDC,
    profit_usd: 1184.9,
    tip_lamports: 92000,
    confidence: 0.9,
    detector: "parsed_swap_arbitrage_orca_whirlpool",
    execution_lane: "priority-fee",
    bundle_likelihood: 0.54,
    evidence: [
      "same signer crossed multiple Orca fee-tier pools",
      "adaptive-fee pool repriced after tick-group movement",
      "net USDC balance remained positive after route completion",
    ],
    frontrun_tx: null,
    victim_tx: null,
    backrun_tx: null,
  },
  {
    id: 204,
    attack_type: "backrun",
    slot: 330100050,
    block_time: new Date(now - 3 * 60 * 1000 - 15 * 1000).toISOString(),
    validator: "Jito-Validator-Whirlpool-03",
    attacker_wallet: "ORCAbackrunTickDrift5mQ1pL6sX2cB9wT3eK7",
    entity_id: null,
    entity_label: null,
    entity_risk: null,
    victim_wallet: "DeskRouteUser3wQ7xL4dJ7cP1eF6gH9wY3zA0",
    victim_loss_usd: 188.44,
    pool_address: OK_WHIRL_JITO_SOL,
    protocol: "orca_whirlpool",
    surface_label: "Orca Whirlpool JITO/SOL",
    token_mint: JITO,
    profit_usd: 529.73,
    tip_lamports: 112000,
    confidence: 0.87,
    detector: "parsed_swap_backrun_orca_whirlpool",
    execution_lane: "jito-aligned",
    bundle_likelihood: 0.69,
    evidence: [
      "large victim swap moved across adjacent tick array",
      "backrun captured post-swap price drift before external venues updated",
      "quote freshness degraded below 180ms on the route window",
    ],
    frontrun_tx: null,
    victim_tx: "OrcaVictimSwapJITOSOL444444444444444444444",
    backrun_tx: "OrcaBackrunJITOSOL44444444444444444444444",
  },
  {
    id: 205,
    attack_type: "sandwich",
    slot: 330100046,
    block_time: new Date(now - 4 * 60 * 1000 - 40 * 1000).toISOString(),
    validator: "Stakewiz-Pro-24",
    attacker_wallet: "ORCAlegacySandwich4vN8mQ1pL6sX2cB9wT3eK",
    entity_id: null,
    entity_label: null,
    entity_risk: null,
    victim_wallet: "StableRouteUser4mP9sX7cT1eH3kF8wQ6yN5dM",
    victim_loss_usd: 116.78,
    pool_address: OK_LEGACY_USDC_USDT,
    protocol: "orca_legacy_v2",
    surface_label: "Orca Legacy USDC/USDT",
    token_mint: USDC,
    profit_usd: 306.54,
    tip_lamports: 36000,
    confidence: 0.84,
    detector: "raw_delta_sandwich_orca_legacy_v2",
    execution_lane: "priority-fee",
    bundle_likelihood: 0.31,
    evidence: [
      "legacy Orca pool bracketed by same signer",
      "victim stable swap paid above expected markout",
      "cleaner Whirlpool stable route was available in candidate set",
    ],
    frontrun_tx: "OrcaLegacyFront555555555555555555555555555",
    victim_tx: "OrcaLegacyVictim55555555555555555555555555",
    backrun_tx: "OrcaLegacyBack555555555555555555555555555",
  },
];

const orcaRoutes: RouteRisk[] = [
  {
    route_key: OK_WHIRL_SOL_USDC,
    route_kind: "venue",
    protocol: "orca_whirlpool",
    label: "Orca Whirlpool SOL/USDC 0.04%",
    sandwich_count: 10,
    arbitrage_count: 22,
    jit_count: 46,
    liquidation_count: 1,
    backrun_count: 12,
    total_attacks: 91,
    total_extracted_usd: 38480,
    unique_attackers: 8,
    avg_confidence: 91,
    bundle_share: 68,
    risk_score: 87,
    recommendation: "avoid",
    execution_quality_score: 24,
    toxic_flow_rate: 82,
    realized_slippage_bps: 9.6,
    stale_quote_pickup_rate: 39,
    quote_freshness_ms: 118,
    markout_1s_bps: 6.8,
    markout_5s_bps: 11.7,
    markout_30s_bps: 18.4,
    flow_quality_score: 18,
    toxicity_probability: 88,
    retail_likelihood: 7,
    lp_adverse_selection_probability: 84,
    lvr_proxy_score: 79,
    priority_fee_pressure: 58,
    validator_markout_quality: 22,
    source_hint: "bundle-lane",
    recommended_max_notional_usd: 16500,
    estimated_savings_bps: 11.2,
    estimated_savings_usd: 156800,
    order_flow_imbalance: 56.8,
    lp_annual_loss_rate_pct: 27.6,
    lp_annual_loss_usd_estimate: 4554,
    policy_action: "avoid",
    reason_codes: ["read_whirlpool_state", "read_tick_arrays", "adaptive_fee_state", "jit_liquidity", "lp_adverse_selection"],
    decomposition: [
      { label: "jit_window_exposure", value: 74 },
      { label: "stale_quote_pickups", value: 39 },
      { label: "bundle_pressure", value: 68 },
      { label: "markout_deterioration", value: 55 },
      { label: "lp_adverse_selection", value: 79 },
    ],
  },
  {
    route_key: OK_WHIRL_MSOL_SOL,
    route_kind: "venue",
    protocol: "orca_whirlpool",
    label: "Orca Whirlpool mSOL/SOL 0.01%",
    sandwich_count: 3,
    arbitrage_count: 35,
    jit_count: 31,
    liquidation_count: 0,
    backrun_count: 8,
    total_attacks: 77,
    total_extracted_usd: 24420,
    unique_attackers: 6,
    avg_confidence: 87,
    bundle_share: 56,
    risk_score: 76,
    recommendation: "penalize",
    execution_quality_score: 38,
    toxic_flow_rate: 67,
    realized_slippage_bps: 5.7,
    stale_quote_pickup_rate: 44,
    quote_freshness_ms: 172,
    markout_1s_bps: 3.9,
    markout_5s_bps: 7.6,
    markout_30s_bps: 12.1,
    flow_quality_score: 33,
    toxicity_probability: 73,
    retail_likelihood: 20,
    lp_adverse_selection_probability: 71,
    lvr_proxy_score: 66,
    priority_fee_pressure: 42,
    validator_markout_quality: 36,
    source_hint: "searcher-bot",
    recommended_max_notional_usd: 36000,
    estimated_savings_bps: 7.4,
    estimated_savings_usd: 92800,
    order_flow_imbalance: 37.4,
    lp_annual_loss_rate_pct: 19.6,
    lp_annual_loss_usd_estimate: 7056,
    policy_action: "reroute",
    reason_codes: ["read_tick_arrays", "jit_liquidity", "lp_adverse_selection", "stale_quote_pickups"],
    decomposition: [
      { label: "jit_window_exposure", value: 61 },
      { label: "stale_quote_pickups", value: 44 },
      { label: "bundle_pressure", value: 56 },
      { label: "markout_deterioration", value: 36 },
      { label: "lp_adverse_selection", value: 66 },
    ],
  },
  {
    route_key: OK_WHIRL_USDC_SOL,
    route_kind: "venue",
    protocol: "orca_whirlpool",
    label: "Orca Whirlpool USDC/SOL adaptive fee",
    sandwich_count: 6,
    arbitrage_count: 43,
    jit_count: 18,
    liquidation_count: 0,
    backrun_count: 18,
    total_attacks: 85,
    total_extracted_usd: 31260,
    unique_attackers: 9,
    avg_confidence: 84,
    bundle_share: 46,
    risk_score: 72,
    recommendation: "penalize",
    execution_quality_score: 42,
    toxic_flow_rate: 63,
    realized_slippage_bps: 6.8,
    stale_quote_pickup_rate: 52,
    quote_freshness_ms: 146,
    markout_1s_bps: 4.8,
    markout_5s_bps: 8.9,
    markout_30s_bps: 13.8,
    flow_quality_score: 39,
    toxicity_probability: 69,
    retail_likelihood: 24,
    lp_adverse_selection_probability: 68,
    lvr_proxy_score: 70,
    priority_fee_pressure: 36,
    validator_markout_quality: 40,
    source_hint: "adaptive-fee",
    recommended_max_notional_usd: 42000,
    estimated_savings_bps: 7.9,
    estimated_savings_usd: 104400,
    order_flow_imbalance: 42.1,
    lp_annual_loss_rate_pct: 20.8,
    lp_annual_loss_usd_estimate: 8736,
    policy_action: "reroute",
    reason_codes: ["adaptive_fee_state", "tick_array_staleness", "stale_quote_pickups", "lp_adverse_selection"],
    decomposition: [
      { label: "jit_window_exposure", value: 38 },
      { label: "stale_quote_pickups", value: 52 },
      { label: "bundle_pressure", value: 46 },
      { label: "markout_deterioration", value: 41 },
      { label: "lp_adverse_selection", value: 70 },
    ],
  },
  {
    route_key: OK_WHIRL_ORCA_SOL,
    route_kind: "venue",
    protocol: "orca_whirlpool",
    label: "Orca Whirlpool ORCA/SOL 0.30%",
    sandwich_count: 4,
    arbitrage_count: 19,
    jit_count: 14,
    liquidation_count: 0,
    backrun_count: 7,
    total_attacks: 44,
    total_extracted_usd: 10440,
    unique_attackers: 5,
    avg_confidence: 78,
    bundle_share: 34,
    risk_score: 58,
    recommendation: "penalize",
    execution_quality_score: 57,
    toxic_flow_rate: 48,
    realized_slippage_bps: 4.2,
    stale_quote_pickup_rate: 31,
    quote_freshness_ms: 254,
    markout_1s_bps: 2.4,
    markout_5s_bps: 4.8,
    markout_30s_bps: 8.1,
    flow_quality_score: 52,
    toxicity_probability: 54,
    retail_likelihood: 36,
    lp_adverse_selection_probability: 48,
    lvr_proxy_score: 46,
    priority_fee_pressure: 27,
    validator_markout_quality: 55,
    source_hint: "searcher-bot",
    recommended_max_notional_usd: 68000,
    estimated_savings_bps: 4.6,
    estimated_savings_usd: 38200,
    order_flow_imbalance: 24.2,
    lp_annual_loss_rate_pct: 11.8,
    lp_annual_loss_usd_estimate: 8024,
    policy_action: "penalize",
    reason_codes: ["read_whirlpool_state", "lp_adverse_selection", "monitor_surface"],
    decomposition: [
      { label: "jit_window_exposure", value: 32 },
      { label: "stale_quote_pickups", value: 31 },
      { label: "bundle_pressure", value: 34 },
      { label: "markout_deterioration", value: 24 },
      { label: "lp_adverse_selection", value: 46 },
    ],
  },
  {
    route_key: OK_LEGACY_USDC_USDT,
    route_kind: "route",
    protocol: "orca_legacy_v2",
    label: "Orca Legacy USDC/USDT",
    sandwich_count: 9,
    arbitrage_count: 37,
    jit_count: 0,
    liquidation_count: 0,
    backrun_count: 9,
    total_attacks: 55,
    total_extracted_usd: 8240,
    unique_attackers: 7,
    avg_confidence: 74,
    bundle_share: 24,
    risk_score: 41,
    recommendation: "monitor",
    execution_quality_score: 69,
    toxic_flow_rate: 34,
    realized_slippage_bps: 1.9,
    stale_quote_pickup_rate: 57,
    quote_freshness_ms: 432,
    markout_1s_bps: 1.1,
    markout_5s_bps: 2.2,
    markout_30s_bps: 4.1,
    flow_quality_score: 63,
    toxicity_probability: 35,
    retail_likelihood: 52,
    lp_adverse_selection_probability: 32,
    lvr_proxy_score: 28,
    priority_fee_pressure: 18,
    validator_markout_quality: 66,
    source_hint: "aggregator-routed",
    recommended_max_notional_usd: 140000,
    estimated_savings_bps: 2.1,
    estimated_savings_usd: 11600,
    order_flow_imbalance: 15.6,
    lp_annual_loss_rate_pct: 5.2,
    lp_annual_loss_usd_estimate: 7280,
    policy_action: "monitor",
    reason_codes: ["stale_quote_pickups", "legacy_pool_watch"],
    decomposition: [
      { label: "sandwich_concentration", value: 16 },
      { label: "stale_quote_pickups", value: 57 },
      { label: "bundle_pressure", value: 24 },
      { label: "markout_deterioration", value: 12 },
      { label: "lp_adverse_selection", value: 28 },
    ],
  },
];

const orcaPools: PoolToxicity[] = orcaRoutes.slice(0, 5).map((route, index) => ({
  pool_address: route.route_key,
  epoch: 718,
  protocol: route.protocol,
  sandwich_count: route.sandwich_count,
  arbitrage_count: route.arbitrage_count,
  jit_count: route.jit_count,
  total_attacks: route.total_attacks,
  total_extracted_usd: route.total_extracted_usd,
  unique_attackers: route.unique_attackers,
  toxicity_score: route.risk_score,
  top_entity_id: index < 3 ? "entity_jit_labs" : null,
  top_entity_label: index < 3 ? "Whirlpool JIT Desk" : "Cross-fee Arbitrage Desk",
  top_entity_risk: index < 3 ? 0.82 : 0.58,
  lvr_proxy_score: route.lvr_proxy_score,
  adverse_selection_intensity: route.lp_adverse_selection_probability,
  stale_quote_arb_frequency: route.stale_quote_pickup_rate,
  lp_drag_estimate_usd: route.lp_annual_loss_usd_estimate + route.total_extracted_usd * 0.42,
  toxic_to_benign_volume_ratio: Number((route.toxicity_probability / Math.max(12, 100 - route.toxicity_probability)).toFixed(2)),
  quote_freshness_stress: Math.max(5, 100 - Math.round(route.quote_freshness_ms / 7)),
  saved_fee_bps_if_segmented: route.estimated_savings_bps,
  primary_cause: route.jit_count > route.sandwich_count ? "whirlpool JIT liquidity" : "stale quote pressure",
  reason_codes: route.reason_codes,
}));

const orcaLpProtection: LpProtectionSnapshot[] = orcaPools.map((pool) => ({
  pool_address: pool.pool_address,
  protocol: pool.protocol,
  toxicity_score: pool.toxicity_score,
  lvr_proxy_score: pool.lvr_proxy_score ?? 0,
  adverse_selection_intensity: pool.adverse_selection_intensity ?? 0,
  stale_quote_arb_frequency: pool.stale_quote_arb_frequency ?? 0,
  lp_drag_estimate_usd: pool.lp_drag_estimate_usd ?? 0,
  toxic_to_benign_volume_ratio: pool.toxic_to_benign_volume_ratio ?? 0,
  quote_freshness_stress: pool.quote_freshness_stress ?? 0,
  saved_fee_bps_if_segmented: pool.saved_fee_bps_if_segmented ?? 0,
  primary_cause: pool.primary_cause ?? "whirlpool adverse selection",
  reason_codes: pool.reason_codes ?? [],
}));

export function getDemoRaydiumAttacks(): Attack[] {
  return raydiumAttacks;
}

export function getDemoRaydiumRoutes(): RouteRisk[] {
  return raydiumRoutes;
}

export function getDemoRaydiumPools(): PoolToxicity[] {
  return raydiumPools;
}

export function getDemoRaydiumLpProtection(): LpProtectionSnapshot[] {
  return raydiumLpProtection;
}

export function getDemoOrcaAttacks(): Attack[] {
  return orcaAttacks;
}

export function getDemoOrcaRoutes(): RouteRisk[] {
  return orcaRoutes;
}

export function getDemoOrcaPools(): PoolToxicity[] {
  return orcaPools;
}

export function getDemoOrcaLpProtection(): LpProtectionSnapshot[] {
  return orcaLpProtection;
}
